import './js/api/api';
import './js/header/header';
import './js/hero/hero';
import './js/cocktailsMarkUp/cocktailsMarkUp';
import './js/searchCocktails/searchCocktails'
import './js/modalCocktails/modalCocktails';
import './js/modalIngredients/modalIngredients';
import './js/header/open-list';
import './js/header/theme';
